<div style="font-family: Times New Roman; font-size: 20px; border-radius : 10px; background-color:rgb(253, 250, 250); color:rgb(0, 25, 135); padding: 12px; line-height: 0.7;">List </div>

In [22]:
# list daftar belanja bulanan di kost
list_belanja=["Sabun", "Tisu", "Odol", "Sunscreen"]
print("List belanja awal:", list_belanja)

List belanja awal: ['Sabun', 'Tisu', 'Odol', 'Sunscreen']


In [23]:
# tambah barang baru
list_belanja.append("Parfume")
print("Setelah tambah barang:", list_belanja)

Setelah tambah barang: ['Sabun', 'Tisu', 'Odol', 'Sunscreen', 'Parfume']


In [24]:
# hapus barang (masih ada di kost)
list_belanja.remove("Odol")
print("Setelah hapus barang:", list_belanja)

Setelah hapus barang: ['Sabun', 'Tisu', 'Sunscreen', 'Parfume']


In [25]:
# update nama barang (typo ki kodong)
list_belanja[1]="Tisu Wajah"
print("Ganti nama barang:", list_belanja)

Ganti nama barang: ['Sabun', 'Tisu Wajah', 'Sunscreen', 'Parfume']


In [26]:
# menampilkan list barang langsung
print("fix belanjaan:", list_belanja)

fix belanjaan: ['Sabun', 'Tisu Wajah', 'Sunscreen', 'Parfume']


<div style="font-family: Times New Roman; font-size: 20px; border-radius : 10px; background-color:rgb(253, 250, 250); color:rgb(0, 25, 135); padding: 12px; line-height: 0.7;">Array </div>

In [27]:
import array as arr
# membuat array bertipe ineteger (harga barang belanja bulanan)
# harga awal
harga=arr.array('i',[20000, 15000, 30000, 40000])

In [28]:
# operasi dasar
harga.append(75000)   #harga produk baru
harga.remove(30000)   #hapus harga yg tidak jadi beli
harga[1]=13500        #update harga (ada diskon)

In [29]:
# menampilkan harga
print("list harga:",end="")
for x in harga:
    print(x,end="")

list harga:20000135004000075000

In [30]:
# list 
list_dihapusdiganti=["Odol",30000,"Tisu",15000]
list_dihapusdiganti.append(True)
print("list dihapusdiganti:",list_dihapusdiganti)

list dihapusdiganti: ['Odol', 30000, 'Tisu', 15000, True]


In [31]:
# Array dengan modul array
harga_array=arr.array('i',[20000, 135000, 40000])
harga_array.append(75000)
print("Fix Harga(module array):",harga_array.tolist())

Fix Harga(module array): [20000, 135000, 40000, 75000]


<div style="font-family: Times New Roman; font-size: 20px; border-radius : 10px; background-color:rgb(253, 250, 250); color:rgb(0, 25, 135); padding: 12px; line-height: 0.7;">Array dengan NumPy </div>

In [32]:
import numpy as np
nilai_tugas=np.array([80, 85, 90, 95, 99])
print("Nilai tugas:", nilai_tugas)
print("Operasi aritmatika(+10):", nilai_tugas+10)

Nilai tugas: [80 85 90 95 99]
Operasi aritmatika(+10): [ 90  95 100 105 109]


In [33]:
# pembuatan array numpy
nilai=np.array([88, 90, 95, 100])
print("Mau nilai:", nilai)

Mau nilai: [ 88  90  95 100]


<div style="font-family: Times New Roman; font-size: 20px; border-radius : 10px; background-color:rgb(253, 250, 250); color:rgb(0, 25, 135); padding: 12px; line-height: 0.7;">Matriks dengan NumPy </div>

In [34]:
# membuat array berisi nol
zeros=np.zeros((3,9))  #array 3x9
print(zeros)

[[0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [35]:
# membuat array berisi satu
ones=np.ones((3,3))
print(ones)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [36]:
# membuat array dengan rentang nilai (seperti range())tapi lebih fleksibel
arr=np.arange(3,9,6)
print(arr)

[3]


In [37]:
# membuat array dengan jumlah elemen tertentu yg dibagi rata dlm suatu interval
linspace=np.linspace(0,10,5)
print(linspace)

[ 0.   2.5  5.   7.5 10. ]


In [38]:
# membuat array dengan nilai acak dari distribusi seragam (0 hingga 1)
random_arr=np.random.randint(0,10, size=(9,9))
print(random_arr)

[[0 3 6 0 0 6 7 7 9]
 [6 5 9 3 1 8 0 5 3]
 [8 0 5 8 2 8 9 2 5]
 [3 3 7 3 2 0 3 9 0]
 [4 6 3 9 1 6 8 4 1]
 [5 3 8 0 9 9 0 5 6]
 [3 6 7 8 7 2 8 9 4]
 [3 3 6 4 1 7 9 8 8]
 [1 5 7 3 6 4 7 2 0]]


In [39]:
# mengetahui bentuk dan dimensi array
a=np.array([[3,9],[0,6]]);a.shape; a.ndim
print(a)

[[3 9]
 [0 6]]


In [40]:
# mengetahui atau mengatur tipe data
tes=np.array([1,2,3],dtype="float32").dtype
print(tes)

float32


In [41]:
# menghitung total elemen
tes=np.array([[0,3],[0,9],[0,6]]).size
print(tes)

6


In [42]:
# akses dan manipulasi data
a=np.array([30,90,60,91]);a[1:3]
print(a)

[30 90 60 91]


<div style="font-family: Times New Roman; font-size: 20px; border-radius : 10px; background-color:rgb(253, 250, 250); color:rgb(0, 25, 135); padding: 12px; line-height: 0.7;">Contoh Penerapan (Pengeluaran Harian) </div>

In [43]:
# import library
import numpy as np

In [44]:
# buat data pengeluaran selama seminggu (Rp)
pengeluaran = np.array([15, 70, 35, 100, 20, 45, 90])

In [45]:
# cek atribut
print("Shape:", pengeluaran.shape)
print("Dimensi:", pengeluaran.ndim)
print("Tipe data:", pengeluaran.dtype)
print("Jumlah data:", pengeluaran.size)

Shape: (7,)
Dimensi: 1
Tipe data: int64
Jumlah data: 7


In [46]:
# slicing
akhir = pengeluaran[-5:]    #ambil 5 hari terakhir
print("5 hari terakhir:", akhir)

5 hari terakhir: [ 35 100  20  45  90]


In [47]:
# cari 2 pengeluaran tertinggi
urut = np.sort(pengeluaran)
tertinggi = urut[-2:]
print("2 pengeluaran tertinggi:", tertinggi)

2 pengeluaran tertinggi: [ 90 100]


In [48]:
# prediksi pengeluaran besok
prediksi = np.zeros(1)
prediksi[0] = np.mean(pengeluaran) + 10
print("Prediksi besok (ribu):", prediksi[0])

Prediksi besok (ribu): 63.57142857142857


<div style="font-family: Times New Roman; font-size: 20px; border-radius : 10px; background-color:rgb(253, 250, 250); color:rgb(0, 25, 135); padding: 12px; line-height: 0.7;">Statistical Functions </div>

<div style="font-family: Times New Roman; font-size: 20px; border-radius : 10px; background-color:rgb(253, 250, 250); color:rgb(0, 25, 135); padding: 12px; line-height: 0.7;">1. Menampilkan Nilai Maksimal dan Minimal </div>

In [49]:
# numpy.amin() and numpy.amax()
arr = np.array([3, 1, 4, 1, 5, 9, 2, 6, 5])
min_value = np.amin(arr)
print("Nilai Minimum:", min_value)

max_value = np.amax(arr)
print("Nilai Maksimum:", max_value)

arr = np.array([3, 1, 4, 1, 5, 9, 2, 6, 5])
max_value = np.amax(arr)
print("Nilai Maksimum:", max_value)

Nilai Minimum: 1
Nilai Maksimum: 9
Nilai Maksimum: 9


<div style="font-family: Times New Roman; font-size: 20px; border-radius : 10px; background-color:rgb(253, 250, 250); color:rgb(0, 25, 135); padding: 12px; line-height: 0.7;">2. Menghitung rentang (range) dari Array </div>

In [50]:
# numpy.ptp()
range_value = np.ptp(arr)
print("\nArray:", arr)
print("Rentang:", range_value)


Array: [3 1 4 1 5 9 2 6 5]
Rentang: 8


<div style="font-family: Times New Roman; font-size: 20px; border-radius : 10px; background-color:rgb(253, 250, 250); color:rgb(0, 25, 135); padding: 12px; line-height: 0.7;">3. Menghitung Persentil </div>

In [51]:
# numpy.percentile()
# membuat array NumPy 
arr = np.array([4, 8, 3, 9, 6, 2, 1, 5, 9])

# menghitung persentil ke-25 (Q1)
q1 = np.percentile(arr, 25)

# menghitung persentil ke-50 (median)
median = np.percentile(arr, 50)

# menghitung persentil ke-75 (Q3)
q3 = np.percentile(arr, 75)

# menampilkan hasil
print("Q1 (Persentil ke-25):", q1)
print("Median (Persentil ke-50):", median)
print("Q3 (Persentil ke-75):", q3)

Q1 (Persentil ke-25): 3.0
Median (Persentil ke-50): 5.0
Q3 (Persentil ke-75): 8.0


<div style="font-family: Times New Roman; font-size: 20px; border-radius : 10px; background-color:rgb(253, 250, 250); color:rgb(0, 25, 135); padding: 12px; line-height: 0.7;">4. Menghitung Median </div>

In [52]:
#4. numpy.median()
# membuat array numpy
arr = np.array([4, 8, 3, 9, 6, 2, 1, 5, 9])

# menggunakan numpy.median() untuk menghitung median
median_value = np.median(arr)
print("Array:", arr)
print("Median:", median_value)

Array: [4 8 3 9 6 2 1 5 9]
Median: 5.0


<div style="font-family: Times New Roman; font-size: 20px; border-radius : 10px; background-color:rgb(253, 250, 250); color:rgb(0, 25, 135); padding: 12px; line-height: 0.7;">5. Menghitung Mean </div>

In [53]:
# numpy.mean()
arr = np.array([4, 8, 3, 9, 6, 2, 1, 5, 9])
mean = np.mean(arr)
print("Mean:", mean)

Mean: 5.222222222222222


<div style="font-family: Times New Roman; font-size: 20px; border-radius : 10px; background-color:rgb(253, 250, 250); color:rgb(0, 25, 135); padding: 12px; line-height: 0.7;">6. Menghitung Average </div>

In [54]:
# numpy.average()
average = np.average(arr)
average = np.average(arr)
print("Average:", average)

Average: 5.222222222222222


<div style="font-family: Times New Roman; font-size: 20px; border-radius : 10px; background-color:rgb(253, 250, 250); color:rgb(0, 25, 135); padding: 12px; line-height: 0.7;">7. Standard Deviation </div>

In [55]:
arr = np.array([4, 8, 3, 9, 6, 2, 1, 5, 9])

# menghitung standar deviasi dari array arr
std_deviation = np.std(arr)

print("Standar Deviasi:", std_deviation)

#7.1. Data berkelompok
interval = np.array([20, 30, 40, 50, 60, 70])  # Batas interval
frekuensi = np.array([5, 12, 18, 10, 7])       # Frekuensi

# menghitung midpoint dari setiap interval
midpoints = (interval[:-1] + interval[1:]) / 2

# menghitung mean dari data berkelompok
mean = np.sum(midpoints * frekuensi) / np.sum(frekuensi)

# menghitung variansi dari data berkelompok
varians = np.sum(((midpoints - mean) ** 2) * frekuensi) / np.sum(frekuensi)

# menghitung standar deviasi dari data berkelompok
std_deviation = np.sqrt(varians)

print("Mean:", mean)
print("Varians:", varians)
print("Standard Deviation:", std_deviation)

Standar Deviasi: 2.8196838978776713
Mean: 45.38461538461539
Varians: 134.46745562130178
Standard Deviation: 11.596010332062566


<div style="font-family: Times New Roman; font-size: 20px; border-radius : 10px; background-color:rgb(253, 250, 250); color:rgb(0, 25, 135); padding: 12px; line-height: 0.7;">8. Variance </div>

In [56]:
# Membuat array NumPy
arr = np.array([4, 8, 3, 9, 6, 2, 1, 5, 9])

# Menghitung varians dari array arr
variance = np.var(arr)

print("Array:", arr)
print("Varians:", variance)

Array: [4 8 3 9 6 2 1 5 9]
Varians: 7.950617283950617
